In [5]:
import streamlit as st
import pandas as pd 
import urllib 
import json
from helpers import *
import folium 
from geopy.geocoders import Nominatim

2025-04-26 15:52:45.170 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

In [6]:
# Example URL to fetch bike share data (replace with the actual URL from the resource_urls list)
station_url = 'https://tor.publicbikesystem.net/ube/gbfs/v1/en/station_status.json'  
latlon_url = "https://tor.publicbikesystem.net/ube/gbfs/v1/en/station_information"

In [9]:
df1 = query_station_status(station_url)

In [10]:
df2 = get_station_latlon(latlon_url)

In [11]:
join_latlon(df1, df2)
# Create a map centered around the average latitude and longitude of the stations

,station_id,num_bikes_available,num_bikes_available_types,num_bikes_disabled,num_docks_available,num_docks_disabled,last_reported,is_charging_station,status,is_installed,is_renting,is_returning,traffic,mechanical,ebike,lat,lon
0,7000,31,"{'mechanical': 30, 'ebike': 1}",1,15,0,2025-04-26 10:51:42,False,IN_SERVICE,1,1,1,None,30,1,43.639832,-79.395954
1,7001,15,"{'mechanical': 1, 'ebike': 14}",7,1,0,2025-04-26 10:50:50,True,IN_SERVICE,1,1,1,None,1,14,43.664964,-79.383550
2,7002,0,"{'mechanical': 0, 'ebike': 0}",0,18,1,2025-04-26 10:52:24,False,IN_SERVICE,1,1,1,None,0,0,43.667131,-79.399555
3,7003,0,"{'mechanical': 0, 'ebike': 0}",0,15,0,2025-04-26 10:52:39,False,IN_SERVICE,1,1,1,None,0,0,43.667018,-79.402796
4,7005,12,"{'mechanical': 12, 'ebike': 0}",1,10,0,2025-04-26 10:52:00,False,IN_SERVICE,1,1,1,None,12,0,43.648001,-79.383177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
872,7266,11,"{'mechanical': 10, 'ebike': 1}",1,0,0,2025-04-26 10:51:35,False,IN_SERVICE,1,1,1,None,10,1,43.695102,-79.289703
873,8022,5,"{'mechanical': 4, 'ebike': 1}",1,3,2,2025-04-26 10:52:00,False,IN_SERVICE,1,1,1,None,4,1,43.719409,-79.302261
874,8023,7,"{'mechanical': 5, 'ebike': 2}",1,3,0,2025-04-26 10:51:15,False,IN_SERVICE,1,1,1,None,5,2,43.655119,-79.420145
875,7133,0,"{'mechanical': 0, 'ebike': 0}",1,9,1,2025-04-26 10:51:49,False,IN_SERVICE,1,1,1,None,0,0,43.682012,-79.391307
876,8024,3,"{'mechanical': 3, 'ebike': 0}",6,1,0,2025-04-26 10:50:56,False,IN_SERVICE,1,1,1,None,3,0,43.661474,-79.426768